<?php

namespace Gtlogistics\X12Parser\Qualifier;

enum AcknowledgmentRequestedCode: string {
    case NO_INTERCHANGE_ACKNOWLEDGMENT_REQUESTED = '0';
    case INTERCHANGE_ACKNOWLEDGMENT_REQUESTED_TA1 = '1';
    case INTERCHANGE_ACKNOWLEDGMENT_REQUESTED_ONLY_WHEN_INTERCHANGE_IS_REJECTED_BECAUSE_OF_ERRORS = '2';
    case INTERCHANGE_ACKNOWLEDGMENT_REQUESTED_ONLY_WHEN_INTERCHANGE_IS_REJECTED_BECAUSE_OF_ERRORS_OR_ACCEPTED_BUT_ERRORS_ARE_NOTED = '3';
}
