<?php

namespace Gtlogistics\X12Parser\Qualifier;

enum AuthorizationInformationQualifier: string {
    case NO_AUTHORIZATION_INFORMATION_PRESENT_NO_MEANINGFUL_INFORMATION_IN_I02 = '00';
    case UCS_COMMUNICATIONS_ID = '01';
    case EDX_COMMUNICATIONS_ID = '02';
    case ADDITIONAL_DATA_IDENTIFICATION = '03';
    case RAIL_COMMUNICATIONS_ID = '04';
    case DEPARTMENT_OF_DEFENSE_DO_D_COMMUNICATION_IDENTIFIER = '05';
    case UNITED_STATES_FEDERAL_GOVERNMENT_COMMUNICATION_IDENTIFIER = '06';
    case TRUCK_COMMUNICATIONS_ID = '07';
    case OCEAN_COMMUNICATIONS_ID = '08';
}
