<?php

namespace Gtlogistics\X12Parser\Qualifier;

enum InterchangeIDQualifier: string {
    case DUNS_DUN_BRADSTREET = '01';
    case SCAC_STANDARD_CARRIER_ALPHA_CODE = '02';
    case FMC_FEDERAL_MARITIME_COMMISSION = '03';
    case IATA_INTERNATIONAL_AIR_TRANSPORT_ASSOCIATION = '04';
    case GLOBAL_LOCATION_NUMBER_GLN = '07';
    case UCCEDI_COMMUNICATIONS_ID_COMM_ID = '08';
    case X121_CCITT = '09';
    case DEPARTMENT_OF_DEFENSE_DO_D_ACTIVITY_ADDRESS_CODE = '10';
    case DEA_DRUG_ENFORCEMENT_ADMINISTRATION = '11';
    case PHONE_TELEPHONE_COMPANIES = '12';
    case UCS_CODE_THE_UCS_CODE_IS_A_CODE_USED_FOR_UCS_TRANSMISSIONS_IT_INCLUDES_THE_AREA_CODE_AND_TELEPHONE_NUMBER_OF_A_MODEM_IT_DOES_NOT_INCLUDE_PUNCTUATION_BLANKS_OR_ACCESS_CODE = '13';
    case DUNS_PLUS_SUFFIX = '14';
    case PETROLEUM_ACCOUNTANTS_SOCIETY_OF_CANADA_COMPANY_CODE = '15';
    case DUNS_NUMBER_WITH4_CHARACTER_SUFFIX = '16';
    case AMERICAN_BANKERS_ASSOCIATION_ABA_TRANSIT_ROUTING_NUMBER_INCLUDING_CHECK_DIGIT9_DIGIT = '17';
    case ASSOCIATION_OF_AMERICAN_RAILROADS_AAR_STANDARD_DISTRIBUTION_CODE = '18';
    case EDI_COUNCIL_OF_AUSTRALIA_EDICA_COMMUNICATIONS_ID_NUMBER_COMMID = '19';
    case HEALTH_INDUSTRY_NUMBER_HIN = '20';
    case INTEGRATED_POSTSECONDARY_EDUCATION_DATA_SYSTEM_OR_IPEDS = '21';
    case FEDERAL_INTERAGENCY_COMMISSION_ON_EDUCATION_OR_FICE = '22';
    case NATIONAL_CENTER_FOR_EDUCATION_STATISTICS_COMMON_CORE_OF_DATA12_DIGIT_NUMBER_FOR_PRE_K_GRADE12_INSTITUTES_OR_NCES = '23';
    case THE_COLLEGE_BOARD_S_ADMISSION_TESTING_PROGRAM4_DIGIT_CODE_OF_POSTSECONDARY_INSTITUTES_OR_ATP = '24';
    case ACT_INC4_DIGIT_CODE_OF_POSTSECONDARY_INSTITUTIONS = '25';
    case STATISTICS_OF_CANADA_LIST_OF_POSTSECONDARY_INSTITUTIONS = '26';
    case CARRIER_IDENTIFICATION_NUMBER_AS_ASSIGNED_BY_CENTERS_FOR_MEDICARE_MEDICAID_SERVICES_CMS = '27';
    case FISCAL_INTERMEDIARY_IDENTIFICATION_NUMBER_AS_ASSIGNED_BY_CENTERS_FOR_MEDICARE_MEDICAID_SERVICES_CMS = '28';
    case MEDICARE_PROVIDER_AND_SUPPLIER_IDENTIFICATION_NUMBER_AS_ASSIGNED_BY_CENTERS_FOR_MEDICARE_MEDICAID_SERVICES_CMS = '29';
    case U_S_FEDERAL_TAX_IDENTIFICATION_NUMBER = '30';
    case JURISDICTION_IDENTIFICATION_NUMBER_PLUS4_AS_ASSIGNED_BY_THE_INTERNATIONAL_ASSOCIATION_OF_INDUSTRIAL_ACCIDENT_BOARDS_AND_COMMISSIONS_IAIABC = '31';
    case U_S_FEDERAL_EMPLOYER_IDENTIFICATION_NUMBER_FEIN = '32';
    case NATIONAL_ASSOCIATION_OF_INSURANCE_COMMISSIONERS_COMPANY_CODE_NAIC = '33';
    case MEDICAID_PROVIDER_AND_SUPPLIER_IDENTIFICATION_NUMBER_AS_ASSIGNED_BY_INDIVIDUAL_STATE_MEDICAID_AGENCIES_IN_CONJUNCTION_WITH_CENTERS_FOR_MEDICARE_MEDICAID_SERVICES_CMS = '34';
    case STATISTICS_CANADA_CANADIAN_COLLEGE_STUDENT_INFORMATION_SYSTEM_INSTITUTION_CODES = '35';
    case STATISTICS_CANADA_UNIVERSITY_STUDENT_INFORMATION_SYSTEM_INSTITUTION_CODES = '36';
    case SOCIETY_OF_PROPERTY_INFORMATION_COMPILERS_AND_ANALYSTS = '37';
    case THE_COLLEGE_BOARD_AND_ACT_INC6_DIGIT_CODE_LIST_OF_SECONDARY_INSTITUTIONS = '38';
    case ASSOCIATION_MEXICANA_DEL_CODIGO_DE_PRODUCTO_AMECOP_COMMUNICATION_ID = 'AM';
    case NATIONAL_RETAIL_MERCHANTS_ASSOCIATION_NRMA_ASSIGNED = 'NR';
    case USER_IDENTIFICATION_NUMBER_AS_ASSIGNED_BY_THE_SAFETY_AND_FITNESS_ELECTRONIC_RECORDS_SAFER_SYSTEM = 'SA';
    case STANDARD_ADDRESS_NUMBER = 'SN';
    case MUTUALLY_DEFINED = 'ZZ';
}
